In [78]:
import pandas as pd
import numpy as np

students = pd.DataFrame({
"student_id":[101,102,103,104,105,106,107,108,109,110],
"name":
["Abel","Sara",None,"John","Marta",None,"David","Helen","Tom",None],
"department":["CS","IT","CS",None,"SE","IT","SE",None,"CS","IT"],
"gpa":[3.5,3.8,np.nan,2.9,3.7,np.nan,3.2,3.4,3.9,np.nan],
"scholarship":
[5000,np.nan,3000,2000,np.nan,4000,3500,np.nan,5000,np.nan]
})

students

   student_id   name department  gpa  scholarship
0         101   Abel         CS  3.5       5000.0
1         102   Sara         IT  3.8          NaN
2         103    NaN         CS  NaN       3000.0
3         104   John        NaN  2.9       2000.0
4         105  Marta         SE  3.7          NaN
5         106    NaN         IT  NaN       4000.0
6         107  David         SE  3.2       3500.0
7         108  Helen        NaN  3.4          NaN
8         109    Tom         CS  3.9       5000.0
9         110    NaN         IT  NaN          NaN

In [79]:
print(students.isnull())
print(students.isnull().sum())
print(students.isnull().sum().sum())
print((students.isnull().sum() / len(students) ) * 100)
print(100 - (
    students.isnull().sum().sum() / students.size
) * 100)

   student_id   name  department    gpa  scholarship
0       False  False       False  False        False
1       False  False       False  False         True
2       False   True       False   True        False
3       False  False        True  False        False
4       False  False       False  False         True
5       False   True       False   True        False
6       False  False       False  False        False
7       False  False        True  False         True
8       False  False       False  False        False
9       False   True       False   True         True
student_id     0
name           3
department     2
gpa            3
scholarship    4
dtype: int64
12
student_id      0.0
name           30.0
department     20.0
gpa            30.0
scholarship    40.0
dtype: float64
76.0

In [80]:
print(students.isnull().sum().idxmax())
print(students.isnull().sum().idxmin())

scholarship
student_id

In [81]:
print(students.columns[students.isnull().any()])
print(students[students.isnull().any(axis=1)])

Index(['name', 'department', 'gpa', 'scholarship'], dtype='str')
   student_id   name department  gpa  scholarship
1         102   Sara         IT  3.8          NaN
2         103    NaN         CS  NaN       3000.0
3         104   John        NaN  2.9       2000.0
4         105  Marta         SE  3.7          NaN
5         106    NaN         IT  NaN       4000.0
7         108  Helen        NaN  3.4          NaN
9         110    NaN         IT  NaN          NaN

In [82]:
print(students[students["gpa"].isnull()])
print(students[students["scholarship"].isnull()])

   student_id name department  gpa  scholarship
2         103  NaN         CS  NaN       3000.0
5         106  NaN         IT  NaN       4000.0
9         110  NaN         IT  NaN          NaN
   student_id   name department  gpa  scholarship
1         102   Sara         IT  3.8          NaN
4         105  Marta         SE  3.7          NaN
7         108  Helen        NaN  3.4          NaN
9         110    NaN         IT  NaN          NaN

In [83]:
students["name"] = students["name"].fillna("Unknown")
students

   student_id     name department  gpa  scholarship
0         101     Abel         CS  3.5       5000.0
1         102     Sara         IT  3.8          NaN
2         103  Unknown         CS  NaN       3000.0
3         104     John        NaN  2.9       2000.0
4         105    Marta         SE  3.7          NaN
5         106  Unknown         IT  NaN       4000.0
6         107    David         SE  3.2       3500.0
7         108    Helen        NaN  3.4          NaN
8         109      Tom         CS  3.9       5000.0
9         110  Unknown         IT  NaN          NaN

In [84]:
students["gpa_missing"] = students["gpa"].isnull()
students

   student_id     name department  gpa  scholarship  gpa_missing
0         101     Abel         CS  3.5       5000.0        False
1         102     Sara         IT  3.8          NaN        False
2         103  Unknown         CS  NaN       3000.0         True
3         104     John        NaN  2.9       2000.0        False
4         105    Marta         SE  3.7          NaN        False
5         106  Unknown         IT  NaN       4000.0         True
6         107    David         SE  3.2       3500.0        False
7         108    Helen        NaN  3.4          NaN        False
8         109      Tom         CS  3.9       5000.0        False
9         110  Unknown         IT  NaN          NaN         True

In [85]:
students["gpa"] = students["gpa"].fillna(students["gpa"].mean())
students["gpa_missing"] = students["gpa"].isnull()

students

   student_id     name department       gpa  scholarship  gpa_missing
0         101     Abel         CS  3.500000       5000.0        False
1         102     Sara         IT  3.800000          NaN        False
2         103  Unknown         CS  3.485714       3000.0        False
3         104     John        NaN  2.900000       2000.0        False
4         105    Marta         SE  3.700000          NaN        False
5         106  Unknown         IT  3.485714       4000.0        False
6         107    David         SE  3.200000       3500.0        False
7         108    Helen        NaN  3.400000          NaN        False
8         109      Tom         CS  3.900000       5000.0        False
9         110  Unknown         IT  3.485714          NaN        False

In [86]:
students["gpa"] = students["gpa"].fillna(students["gpa"].median())
students

   student_id     name department       gpa  scholarship  gpa_missing
0         101     Abel         CS  3.500000       5000.0        False
1         102     Sara         IT  3.800000          NaN        False
2         103  Unknown         CS  3.485714       3000.0        False
3         104     John        NaN  2.900000       2000.0        False
4         105    Marta         SE  3.700000          NaN        False
5         106  Unknown         IT  3.485714       4000.0        False
6         107    David         SE  3.200000       3500.0        False
7         108    Helen        NaN  3.400000          NaN        False
8         109      Tom         CS  3.900000       5000.0        False
9         110  Unknown         IT  3.485714          NaN        False

In [87]:
students["department"] = students["department"].fillna(students["department"].mode()[0])
students

   student_id     name department       gpa  scholarship  gpa_missing
0         101     Abel         CS  3.500000       5000.0        False
1         102     Sara         IT  3.800000          NaN        False
2         103  Unknown         CS  3.485714       3000.0        False
3         104     John         CS  2.900000       2000.0        False
4         105    Marta         SE  3.700000          NaN        False
5         106  Unknown         IT  3.485714       4000.0        False
6         107    David         SE  3.200000       3500.0        False
7         108    Helen         CS  3.400000          NaN        False
8         109      Tom         CS  3.900000       5000.0        False
9         110  Unknown         IT  3.485714          NaN        False

In [88]:
students["scholarship_missing"] = students["scholarship"].isnull()
students

,student_id,name,department,gpa,scholarship,gpa_missing,scholarship_missing
0,101,Abel,CS,3.500000,5000.0,False,False
1,102,Sara,IT,3.800000,NaN,False,True
2,103,Unknown,CS,3.485714,3000.0,False,False
3,104,John,CS,2.900000,2000.0,False,False
4,105,Marta,SE,3.700000,NaN,False,True
5,106,Unknown,IT,3.485714,4000.0,False,False
6,107,David,SE,3.200000,3500.0,False,False
7,108,Helen,CS,3.400000,NaN,False,True
8,109,Tom,CS,3.900000,5000.0,False,False
9,110,Unknown,IT,3.485714,NaN,False,True

In [89]:
students["scholarship"] = students["scholarship"].fillna(0)
students["scholarship_missing"] = students["scholarship"].isnull()

students

,student_id,name,department,gpa,scholarship,gpa_missing,scholarship_missing
0,101,Abel,CS,3.500000,5000.0,False,False
1,102,Sara,IT,3.800000,0.0,False,False
2,103,Unknown,CS,3.485714,3000.0,False,False
3,104,John,CS,2.900000,2000.0,False,False
4,105,Marta,SE,3.700000,0.0,False,False
5,106,Unknown,IT,3.485714,4000.0,False,False
6,107,David,SE,3.200000,3500.0,False,False
7,108,Helen,CS,3.400000,0.0,False,False
8,109,Tom,CS,3.900000,5000.0,False,False
9,110,Unknown,IT,3.485714,0.0,False,False

In [90]:
students.dropna()

,student_id,name,department,gpa,scholarship,gpa_missing,scholarship_missing
0,101,Abel,CS,3.500000,5000.0,False,False
1,102,Sara,IT,3.800000,0.0,False,False
2,103,Unknown,CS,3.485714,3000.0,False,False
3,104,John,CS,2.900000,2000.0,False,False
4,105,Marta,SE,3.700000,0.0,False,False
5,106,Unknown,IT,3.485714,4000.0,False,False
6,107,David,SE,3.200000,3500.0,False,False
7,108,Helen,CS,3.400000,0.0,False,False
8,109,Tom,CS,3.900000,5000.0,False,False
9,110,Unknown,IT,3.485714,0.0,False,False

In [91]:
students.dropna(axis=1)

,student_id,name,department,gpa,scholarship,gpa_missing,scholarship_missing
0,101,Abel,CS,3.500000,5000.0,False,False
1,102,Sara,IT,3.800000,0.0,False,False
2,103,Unknown,CS,3.485714,3000.0,False,False
3,104,John,CS,2.900000,2000.0,False,False
4,105,Marta,SE,3.700000,0.0,False,False
5,106,Unknown,IT,3.485714,4000.0,False,False
6,107,David,SE,3.200000,3500.0,False,False
7,108,Helen,CS,3.400000,0.0,False,False
8,109,Tom,CS,3.900000,5000.0,False,False
9,110,Unknown,IT,3.485714,0.0,False,False

In [92]:
100 - (
    students.isnull().sum().sum() / students.size
) * 100

np.float64(100.0)